const StyleDictionary = require('style-dictionary');
const fs = require('fs');
const path = require('path');

// ─────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────

/**
 * Extract mode data from tokens for a specific collection.
 * Returns: { modeName: [ { token, value }, ... ] }
 */
function extractModes(tokens, collectionName) {
  const modes = {};

  tokens.forEach((token) => {
    const figmaExt = token.$extensions?.figma;
    const tokenCollection = figmaExt?.collection?.name;
    const modeData = token.$extensions?.mode;

    if (tokenCollection !== collectionName || !modeData) return;

    Object.entries(modeData).forEach(([modeName, modeValue]) => {
      if (!modes[modeName]) modes[modeName] = [];
      modes[modeName].push({
        token,
        value: modeValue,
        varName: `--${token.path.join('-')}`,
      });
    });
  });

  return modes;
}

/**
 * Resolve a token reference like "{font.size.fs+7}" to its value.
 */
function resolveReference(ref, dictionary) {
  const cleanRef = ref.replace(/[{}]/g, '');
  const found = dictionary.allTokens.find(
    (t) => t.path.join('.') === cleanRef
  );
  return found ? found.$value : ref;
}

/**
 * Get the final resolved value for a token, handling references.
 */
function getResolvedValue(token, dictionary) {
  let value = token.$value;
  if (typeof value === 'string' && value.startsWith('{')) {
    value = resolveReference(value, dictionary);
  }
  return value;
}

// ─────────────────────────────────────────────────────────────
// CUSTOM TRANSFORMS
// ─────────────────────────────────────────────────────────────

StyleDictionary.registerTransform({
  name: 'size/pxToRem',
  type: 'value',
  transitive: true,
  matcher: (token) =>
    token.$type === 'dimension' &&
    (token.scopes?.includes('FONT_SIZE') ||
      token.path.some((p) => p.toLowerCase().includes('size'))),
  transformer: (token) => {
    const val = parseFloat(token.$value);
    if (isNaN(val)) return token.$value;
    return `${val / 16}rem`;
  },
});

StyleDictionary.registerTransform({
  name: 'font/familyQuote',
  type: 'value',
  transitive: true,
  matcher: (token) => token.$type === 'string' && token.scopes?.includes('FONT_FAMILY'),
  transformer: (token) => {
    const val = token.$value;
    // Don't quote if already has fallback or is a CSS var
    if (val.includes(',') || val.startsWith('var(')) return val;
    return `'${val}', sans-serif`;
  },
});

// ─────────────────────────────────────────────────────────────
// CUSTOM FORMATTERS
// ─────────────────────────────────────────────────────────────

/**
 * CSS: Single file with mode layers (standard global approach)
 * - Default values (lightMode, sans, desktop baseline)
 * - [data-theme="dark"] overrides
 * - [data-typeface="..."] overrides
 * - @media for responsive font sizes
 */
StyleDictionary.registerFormat({
  name: 'css/standard-modes',
  formatter: ({ dictionary }) => {
    const allTokens = dictionary.allTokens;

    // Collect tokens by category
    const colorTokens = allTokens.filter((t) => t.$type === 'color');
    const fontFamilyTokens = allTokens.filter(
      (t) => t.$type === 'string' && t.scopes?.includes('FONT_FAMILY')
    );
    const fontSizeTokens = allTokens.filter(
      (t) =>
        t.$type === 'dimension' &&
        (t.scopes?.includes('FONT_SIZE') || t.path.some((p) => p.toLowerCase().includes('size')))
    );
    const typographyComposites = allTokens.filter((t) => t.$type === 'typography');

    // Extract modes
    const colourModes = extractModes(colorTokens, 'Colour Theme');
    const typefaceModes = extractModes(
      allTokens.filter((t) => t.path.join('.') === 'fontFamilyMode'),
      'Typeface'
    );

    let css = `/* ─────────────────────────────────────────── */
`;
    css += `/* Design Tokens — Auto-generated by Style Dictionary */
`;
    css += `/* Source: source-tokens/tokens.json */
`;
    css += `/* ─────────────────────────────────────────── */

`;

    // ── BASE LAYER (lightMode defaults) ──
    css += `:root {
`;

    // Colors (lightMode defaults)
    colorTokens.forEach((t) => {
      const val = getResolvedValue(t, dictionary);
      css += `  --${t.path.join('-')}: ${val};
`;
    });

    // Font families (sans default)
    const fontFamilyMode = allTokens.find((t) => t.path.join('.') === 'fontFamilyMode');
    if (fontFamilyMode) {
      const defaultFamily = getResolvedValue(fontFamilyMode, dictionary);
      css += `  --font-family-base: ${defaultFamily};
`;
    }

    // Primitive font sizes
    fontSizeTokens.forEach((t) => {
      const val = getResolvedValue(t, dictionary);
      css += `  --${t.path.join('-')}: ${val};
`;
    });

    // Typography composites
    typographyComposites.forEach((t) => {
      const v = t.$value;
      const basePath = t.path.join('-');
      Object.entries(v).forEach(([prop, propVal]) => {
        if (typeof propVal === 'string' && propVal.startsWith('{')) {
          propVal = resolveReference(propVal, dictionary);
        }
        css += `  --${basePath}-${prop}: ${propVal};
`;
      });
    });

    // Spacing / dimensions
    allTokens
      .filter((t) => t.$type === 'dimension' && t.scopes?.includes('GAP'))
      .forEach((t) => {
        const val = getResolvedValue(t, dictionary);
        css += `  --${t.path.join('-')}: ${val};
`;
      });

    // Radius
    allTokens
      .filter((t) => t.$type === 'dimension' && t.scopes?.includes('CORNER_RADIUS'))
      .forEach((t) => {
        const val = getResolvedValue(t, dictionary);
        css += `  --${t.path.join('-')}: ${val};
`;
      });

    css += `}

`;

    // ── DARK MODE LAYER ──
    if (colourModes.darkMode) {
      css += `[data-theme="dark"] {
`;
      colourModes.darkMode.forEach(({ token, value }) => {
        let resolved = value;
        if (typeof value === 'string' && value.startsWith('{')) {
          resolved = resolveReference(value, dictionary);
        }
        css += `  --${token.path.join('-')}: ${resolved};
`;
      });
      css += `}

`;
    }

    // ── TYPEFACE MODE LAYERS ──
    Object.entries(typefaceModes).forEach(([modeName, items]) => {
      if (modeName === 'sans') return; // skip default
      css += `[data-typeface="${modeName}"] {
`;
      items.forEach(({ token, value }) => {
        let resolved = value;
        if (typeof value === 'string' && value.startsWith('{')) {
          resolved = resolveReference(value, dictionary);
        }
        css += `  --font-family-base: ${resolved};
`;
      });
      css += `}

`;
    });

    // ── RESPONSIVE FONT SIZES ──
    // Extract fontSizeMode responsive breakpoints
    const fontSizeModes = allTokens.filter((t) => t.path[0] === 'fontSizeMode');
    const breakpoints = {
      mobile: '393px',
      tablet: '800px',
      desktop: '1280px',
      large: '1440px',
    };

    // Build responsive font size map from fontSizeMode tokens
    const responsiveSizes = {};
    fontSizeModes.forEach((t) => {
      const modeData = t.$extensions?.mode;
      if (!modeData) return;

      const tokenPath = t.path.slice(1).join('-'); // e.g., "heading-h1"
      if (!responsiveSizes[tokenPath]) responsiveSizes[tokenPath] = {};

      Object.entries(modeData).forEach(([bp, ref]) => {
        let resolved = ref;
        if (typeof ref === 'string' && ref.startsWith('{')) {
          resolved = resolveReference(ref, dictionary);
        }
        responsiveSizes[tokenPath][bp] = resolved;
      });
    });

    // Generate media queries
    Object.entries(breakpoints).forEach(([bp, width]) => {
      if (bp === 'mobile') return; // mobile is default (:root)
      css += `@media (min-width: ${width}) {
`;
      css += `  :root {
`;
      Object.entries(responsiveSizes).forEach(([tokenPath, sizes]) => {
        if (sizes[bp]) {
          css += `    --font-size-mode-${tokenPath}: ${sizes[bp]};
`;
        }
      });
      css += `  }
`;
      css += `}

`;
    });

    // ── UTILITY: Typography shorthand classes ──
    css += `/* Typography shorthand classes */
`;
    typographyComposites.forEach((t) => {
      const className = `.typography-${t.path.join('-')}`;
      const v = t.$value;
      css += `${className} {
`;
      css += `  font-family: var(--${t.path.join('-')}-fontFamily);
`;
      css += `  font-weight: var(--${t.path.join('-')}-fontWeight);
`;
      css += `  font-size: var(--${t.path.join('-')}-fontSize);
`;
      css += `  line-height: var(--${t.path.join('-')}-lineHeight);
`;
      css += `  letter-spacing: var(--${t.path.join('-')}-letterSpacing);
`;
      css += `}

`;
    });

    return css;
  },
});

/**
 * Tailwind: Theme config referencing CSS variables
 */
StyleDictionary.registerFormat({
  name: 'tailwind/standard-modes',
  formatter: ({ dictionary }) => {
    const allTokens = dictionary.allTokens;

    // Extract colors
    const colors = {};
    allTokens
      .filter((t) => t.$type === 'color' && (t.path[0] === 'hues' || t.path[0] === 'textColour' || t.path[0] === 'bgColour'))
      .forEach((t) => {
        const key = t.path.slice(1).join('-');
        colors[key] = `var(--${t.path.join('-')})`;
      });

    // Extract font families
    const fontFamily = {};
    allTokens
      .filter((t) => t.path.join('.') === 'fontFamilyMode')
      .forEach((t) => {
        const modeData = t.$extensions?.mode;
        if (modeData) {
          Object.entries(modeData).forEach(([modeName, ref]) => {
            let resolved = ref;
            if (typeof ref === 'string' && ref.startsWith('{')) {
              resolved = resolveReference(ref, dictionary);
            }
            fontFamily[modeName] = [resolved, 'sans-serif'];
          });
        }
      });

    // Extract font sizes (primitive + responsive)
    const fontSize = {};
    allTokens
      .filter((t) => t.$type === 'dimension' && t.scopes?.includes('FONT_SIZE'))
      .forEach((t) => {
        const key = t.path.slice(1).join('-'); // e.g., "size-fs+7"
        const val = getResolvedValue(t, dictionary);
        fontSize[key] = val;
      });

    // Typography composites for Tailwind plugin-style config
    const typography = {};
    allTokens
      .filter((t) => t.$type === 'typography')
      .forEach((t) => {
        const key = t.path.join('-');
        const v = t.$value;
        typography[key] = {
          css: {
            fontFamily: `var(--${key}-fontFamily)`,
            fontWeight: `var(--${key}-fontWeight)`,
            fontSize: `var(--${key}-fontSize)`,
            lineHeight: `var(--${key}-lineHeight)`,
            letterSpacing: `var(--${key}-letterSpacing)`,
          },
        };
      });

    // Spacing
    const spacing = {};
    allTokens
      .filter((t) => t.$type === 'dimension' && t.scopes?.includes('GAP'))
      .forEach((t) => {
        const key = t.path.slice(1).join('-');
        spacing[key] = getResolvedValue(t, dictionary);
      });

    // Border radius
    const borderRadius = {};
    allTokens
      .filter((t) => t.$type === 'dimension' && t.scopes?.includes('CORNER_RADIUS'))
      .forEach((t) => {
        const key = t.path.slice(1).join('-');
        borderRadius[key] = getResolvedValue(t, dictionary);
      });

    return `/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./src/**/*.{html,js,jsx,ts,tsx,vue,svelte}'],
  theme: {
    extend: {
      colors: ${JSON.stringify(colors, null, 6)},
      fontFamily: ${JSON.stringify(fontFamily, null, 6)},
      fontSize: ${JSON.stringify(fontSize, null, 6)},
      spacing: ${JSON.stringify(spacing, null, 6)},
      borderRadius: ${JSON.stringify(borderRadius, null, 6)},
    },
  },
  plugins: [
    require('@tailwindcss/typography')({
      theme: ${JSON.stringify(typography, null, 6)},
    }),
  ],
};`;
  },
});

/**
 * Flutter: Theme with runtime mode switching
 */
StyleDictionary.registerFormat({
  name: 'flutter/standard-modes',
  formatter: ({ dictionary }) => {
    const allTokens = dictionary.allTokens;

    // Extract colour modes
    const colourModes = extractModes(
      allTokens.filter((t) => t.$type === 'color'),
      'Colour Theme'
    );

    // Extract typeface modes
    const typefaceModes = extractModes(
      allTokens.filter((t) => t.path.join('.') === 'fontFamilyMode'),
      'Typeface'
    );

    // Extract primitive colours
    const hueColors = {};
    allTokens
      .filter((t) => t.$type === 'color' && t.path[0] === 'hues')
      .forEach((t) => {
        const key = t.path.slice(1).join('_');
        hueColors[key] = t.$value;
      });

    // Typography composites
    const typographyLines = [];
    allTokens
      .filter((t) => t.$type === 'typography')
      .forEach((t) => {
        const className = t.path
          .map((p) => p[0].toUpperCase() + p.slice(1))
          .join('');
        const v = t.$value;

        const fontFamily = v.fontFamily?.startsWith('{')
          ? resolveReference(v.fontFamily, dictionary)
          : v.fontFamily;
        const fontWeight = v.fontWeight?.startsWith('{')
          ? resolveReference(v.fontWeight, dictionary)
          : v.fontWeight;
        const fontSize = v.fontSize?.startsWith('{')
          ? resolveReference(v.fontSize, dictionary)
          : v.fontSize;
        const lineHeight = v.lineHeight?.startsWith('{')
          ? resolveReference(v.lineHeight, dictionary)
          : v.lineHeight;
        const letterSpacing = v.letterSpacing?.startsWith('{')
          ? resolveReference(v.letterSpacing, dictionary)
          : v.letterSpacing;

        typographyLines.push(`  static const TextStyle ${className} = TextStyle(
    fontFamily: '${fontFamily}',
    fontWeight: FontWeight.w${fontWeight},
    fontSize: ${parseFloat(fontSize || '16')},
    height: ${parseFloat(lineHeight || '1.5')},
    letterSpacing: ${parseFloat(letterSpacing || '0')},
  );`);
      });

    // Generate colour mode maps
    const colourModeEntries = Object.entries(colourModes).map(([modeName, items]) => {
      const entries = items
        .map(({ token, value }) => {
          let resolved = value;
          if (typeof value === 'string' && value.startsWith('{')) {
            resolved = resolveReference(value, dictionary);
          }
          const key = token.path.join('_');
          return `      '${key}': Color(0xFF${resolved.replace('#', '')})`;
        })
        .join(',
');
      return `    '${modeName}': {
${entries}
    }`;
    });

    // Generate typeface mode map
    const typefaceEntries = Object.entries(typefaceModes).map(([modeName, items]) => {
      const val = items[0]?.value;
      let resolved = val;
      if (typeof val === 'string' && val.startsWith('{')) {
        resolved = resolveReference(val, dictionary);
      }
      return `    '${modeName}': '${resolved}'`;
    });

    return `import 'package:flutter/material.dart';

// ───────────────────────────────────────────
// Design Tokens — Auto-generated
// Source: source-tokens/tokens.json
// ───────────────────────────────────────────

class AppTokens {
  // Primitive Colours
${Object.entries(hueColors)
  .map(([k, v]) => `  static const Color ${k} = Color(0xFF${v.replace('#', '')});`)
  .join('
')}

  // Colour Modes
  static const Map<String, Map<String, Color>> colourModes = {
${colourModeEntries.join(',
')}
  };

  // Typeface Modes
  static const Map<String, String> typefaceModes = {
${typefaceEntries.join(',
')}
  };

  // Typography Styles
${typographyLines.join('

')}

  // Theme Builder
  static ThemeData buildTheme({
    String colourMode = 'lightMode',
    String typefaceMode = 'sans',
  }) {
    final colours = colourModes[colourMode]!;
    final fontFamily = typefaceModes[typefaceMode]!;

    return ThemeData(
      brightness: colourMode == 'darkMode' ? Brightness.dark : Brightness.light,
      fontFamily: fontFamily,
      textTheme: TextTheme(
        displayLarge: DisplayLg.copyWith(fontFamily: fontFamily),
        displaySmall: DisplaySm.copyWith(fontFamily: fontFamily),
        headlineLarge: HeadingLg.copyWith(fontFamily: fontFamily),
        headlineSmall: HeadingSm.copyWith(fontFamily: fontFamily),
        titleLarge: TitleLg.copyWith(fontFamily: fontFamily),
        titleSmall: TitleSm.copyWith(fontFamily: fontFamily),
        bodyLarge: BodyLg.copyWith(fontFamily: fontFamily),
        bodyMedium: BodyDefault.copyWith(fontFamily: fontFamily),
        bodySmall: BodySm.copyWith(fontFamily: fontFamily),
        labelLarge: LabelLg.copyWith(fontFamily: fontFamily),
        labelMedium: LabelDefault.copyWith(fontFamily: fontFamily),
        labelSmall: LabelSm.copyWith(fontFamily: fontFamily),
      ),
      colorScheme: ColorScheme(
        brightness: colourMode == 'darkMode' ? Brightness.dark : Brightness.light,
        surface: colours['bgColour_generic'] ?? colours['hues_gray_000'] ?? Colors.white,
        onSurface: colours['textColour_neutral'] ?? colours['hues_gray_1000'] ?? Colors.black,
      ),
    );
  }
}
`;
  },
});

/**
 * Kotlin: Material3 with CompositionLocal
 */
StyleDictionary.registerFormat({
  name: 'kotlin/standard-modes',
  formatter: ({ dictionary }) => {
    const allTokens = dictionary.allTokens;

    const colourModes = extractModes(
      allTokens.filter((t) => t.$type === 'color'),
      'Colour Theme'
    );

    const typefaceModes = extractModes(
      allTokens.filter((t) => t.path.join('.') === 'fontFamilyMode'),
      'Typeface'
    );

    // Hue colours
    const hueColors = {};
    allTokens
      .filter((t) => t.$type === 'color' && t.path[0] === 'hues')
      .forEach((t) => {
        const key = t.path.slice(1).join('_');
        hueColors[key] = t.$value;
      });

    // Typography
    const typographyLines = [];
    allTokens
      .filter((t) => t.$type === 'typography')
      .forEach((t) => {
        const name = t.path
          .map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1)))
          .join('');
        const v = t.$value;

        const fontFamily = v.fontFamily?.startsWith('{')
          ? resolveReference(v.fontFamily, dictionary)
          : v.fontFamily;
        const fontWeight = v.fontWeight?.startsWith('{')
          ? resolveReference(v.fontWeight, dictionary)
          : v.fontWeight;
        const fontSize = v.fontSize?.startsWith('{')
          ? resolveReference(v.fontSize, dictionary)
          : v.fontSize;
        const lineHeight = v.lineHeight?.startsWith('{')
          ? resolveReference(v.lineHeight, dictionary)
          : v.lineHeight;
        const letterSpacing = v.letterSpacing?.startsWith('{')
          ? resolveReference(v.letterSpacing, dictionary)
          : v.letterSpacing;

        typographyLines.push(`    val ${name} = TextStyle(
        fontFamily = FontFamily.${fontFamily?.replace(/\s+/g, '') || 'Default'},
        fontWeight = FontWeight.W${fontWeight || '400'},
        fontSize = ${parseFloat(fontSize || '16')}.sp,
        lineHeight = ${parseFloat(lineHeight || '1.5')}.em,
        letterSpacing = ${parseFloat(letterSpacing || '0')}.em
    )`);
      });

    // Colour scheme builders
    const colourSchemeBuilders = Object.entries(colourModes).map(([modeName, items]) => {
      const isDark = modeName === 'darkMode';
      const surfaceEntry = items.find(({ token }) => token.path.join('_') === 'bgColour_generic');
      const onSurfaceEntry = items.find(({ token }) => token.path.join('_') === 'textColour_neutral');

      const surface = surfaceEntry
        ? surfaceEntry.value.startsWith('{')
          ? resolveReference(surfaceEntry.value, dictionary)
          : surfaceEntry.value
        : isDark ? '#000000' : '#ffffff';
      const onSurface = onSurfaceEntry
        ? onSurfaceEntry.value.startsWith('{')
          ? resolveReference(onSurfaceEntry.value, dictionary)
          : onSurfaceEntry.value
        : isDark ? '#ffffff' : '#000000';

      return `fun ${modeName.replace('Mode', '')}ColorScheme() = ${isDark ? 'darkColorScheme' : 'lightColorScheme'}(
        surface = Color(0xFF${surface.replace('#', '')}),
        onSurface = Color(0xFF${onSurface.replace('#', '')})
    )`;
    });

    // Typeface map
    const typefaceMap = Object.entries(typefaceModes).map(([modeName, items]) => {
      const val = items[0]?.value;
      let resolved = val;
      if (typeof val === 'string' && val.startsWith('{')) {
        resolved = resolveReference(val, dictionary);
      }
      return `        ${modeName.uppercase()} to FontFamily.${resolved?.replace(/\s+/g, '') || 'Default'}`;
    });

    return `package com.example.tokens

import androidx.compose.material3.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

// ───────────────────────────────────────────
// Design Tokens — Auto-generated
// Source: source-tokens/tokens.json
// ───────────────────────────────────────────

object AppTokens {

    // Primitive Colours
${Object.entries(hueColors)
  .map(([k, v]) => `    val ${k} = Color(0xFF${v.replace('#', '')})`)
  .join('
')}

    // Colour Schemes
${colourSchemeBuilders.join('

')}

    // Typeface Modes
    enum class TypefaceMode {
        SANS, SERIF, MONO, PLAYFUL, SCRIPT, GROTESQUE
    }

    private val typefaceMap = mapOf(
${typefaceMap.join(',
')}
    )

    // Typography
    object Typography {
${typographyLines.join('

')}
    }

    // Theme Builder
    @Composable
    fun AppTheme(
        colourMode: String = "lightMode",
        typefaceMode: TypefaceMode = TypefaceMode.SANS,
        content: @Composable () -> Unit
    ) {
        val colorScheme = when (colourMode) {
            "darkMode" -> darkColorScheme()
            else -> lightColorScheme()
        }

        MaterialTheme(
            colorScheme = colorScheme,
            typography = androidx.compose.material3.Typography(
                displayLarge = Typography.DisplayLg,
                displayMedium = Typography.DisplaySm,
                headlineLarge = Typography.HeadingLg,
                headlineMedium = Typography.HeadingSm,
                titleLarge = Typography.TitleLg,
                titleMedium = Typography.TitleSm,
                bodyLarge = Typography.BodyLg,
                bodyMedium = Typography.BodyDefault,
                bodySmall = Typography.BodySm,
                labelLarge = Typography.LabelLg,
                labelMedium = Typography.LabelDefault,
                labelSmall = Typography.LabelSm,
            ),
            content = content
        )
    }
}
`;
  },
});

/**
 * Swift: EnvironmentValues with runtime mode switching
 */
StyleDictionary.registerFormat({
  name: 'swift/standard-modes',
  formatter: ({ dictionary }) => {
    const allTokens = dictionary.allTokens;

    const colourModes = extractModes(
      allTokens.filter((t) => t.$type === 'color'),
      'Colour Theme'
    );

    const typefaceModes = extractModes(
      allTokens.filter((t) => t.path.join('.') === 'fontFamilyMode'),
      'Typeface'
    );

    // Hue colours
    const hueColors = {};
    allTokens
      .filter((t) => t.$type === 'color' && t.path[0] === 'hues')
      .forEach((t) => {
        const key = t.path.slice(1).join('_');
        hueColors[key] = t.$value;
      });

    // Typography
    const typographyLines = [];
    allTokens
      .filter((t) => t.$type === 'typography')
      .forEach((t) => {
        const name = t.path
          .map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1)))
          .join('');
        const v = t.$value;

        const fontFamily = v.fontFamily?.startsWith('{')
          ? resolveReference(v.fontFamily, dictionary)
          : v.fontFamily;
        const fontWeight = v.fontWeight?.startsWith('{')
          ? resolveReference(v.fontWeight, dictionary)
          : v.fontWeight;
        const fontSize = v.fontSize?.startsWith('{')
          ? resolveReference(v.fontSize, dictionary)
          : v.fontSize;
        const lineHeight = v.lineHeight?.startsWith('{')
          ? resolveReference(v.lineHeight, dictionary)
          : v.lineHeight;
        const letterSpacing = v.letterSpacing?.startsWith('{')
          ? resolveReference(v.letterSpacing, dictionary)
          : v.letterSpacing;

        const weightName =
          fontWeight === '700'
            ? 'bold'
            : fontWeight === '600'
            ? 'semibold'
            : fontWeight === '500'
            ? 'medium'
            : 'regular';

        typographyLines.push(`    static let ${name} = Font.custom("${fontFamily}", size: ${parseFloat(fontSize || '16')})
        .weight(.${weightName})`);
      });

    // Colour mode functions
    const colourModeFuncs = Object.entries(colourModes).map(([modeName, items]) => {
      const entries = items
        .map(({ token, value }) => {
          let resolved = value;
          if (typeof value === 'string' && value.startsWith('{')) {
            resolved = resolveReference(value, dictionary);
          }
          const key = token.path.join('_');
          return `            "${key}": Color(hex: "${resolved}")`;
        })
        .join(',
');
      return `        case .${modeName.replace('Mode', '').lowercased()}:
            return [
${entries}
            ]`;
    });

    // Typeface enum
    const typefaceCases = Object.entries(typefaceModes).map(([modeName, items]) => {
      const val = items[0]?.value;
      let resolved = val;
      if (typeof val === 'string' && val.startsWith('{')) {
        resolved = resolveReference(val, dictionary);
      }
      return `        case .${modeName}:
            return "${resolved}"`;
    });

    return `import SwiftUI

// ───────────────────────────────────────────
// Design Tokens — Auto-generated
// Source: source-tokens/tokens.json
// ───────────────────────────────────────────

// MARK: - Colour Extension
extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let a, r, g, b: UInt64
        switch hex.count {
        case 3: // RGB (12-bit)
            (a, r, g, b) = (255, (int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6: // RGB (24-bit)
            (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        case 8: // ARGB (32-bit)
            (a, r, g, b) = (int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (a, r, g, b) = (1, 1, 1, 0)
        }
        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue: Double(b) / 255,
            opacity: Double(a) / 255
        )
    }
}

// MARK: - Token Modes
enum ColourMode: String, CaseIterable {
    case light, dark
}

enum TypefaceMode: String, CaseIterable {
    case sans, serif, mono, playful, script, grotesque
}

// MARK: - Tokens
enum Tokens {

    // Primitive Colours
${Object.entries(hueColors)
  .map(([k, v]) => `    static let ${k} = Color(hex: "${v}")`)
  .join('
')}

    // Colour Mode Resolution
    static func colours(for mode: ColourMode) -> [String: Color] {
        switch mode {
${colourModeFuncs.join('
')}
        }
    }

    // Typeface Mode Resolution
    static func fontFamily(for mode: TypefaceMode) -> String {
        switch mode {
${typefaceCases.join('
')}
        }
    }

    // Typography Styles
${typographyLines.join('

')}
}

// MARK: - Environment Keys
private struct ColourModeKey: EnvironmentKey {
    static let defaultValue: ColourMode = .light
}

private struct TypefaceModeKey: EnvironmentKey {
    static let defaultValue: TypefaceMode = .sans
}

extension EnvironmentValues {
    var colourMode: ColourMode {
        get { self[ColourModeKey.self] }
        set { self[ColourModeKey.self] = newValue }
    }

    var typefaceMode: TypefaceMode {
        get { self[TypefaceModeKey.self] }
        set { self[TypefaceModeKey.self] = newValue }
    }
}

// MARK: - View Modifiers
struct TokenThemeModifier: ViewModifier {
    let colourMode: ColourMode
    let typefaceMode: TypefaceMode

    func body(content: Content) -> some View {
        content
            .environment(\.colourMode, colourMode)
            .environment(\.typefaceMode, typefaceMode)
    }
}

extension View {
    func tokenTheme(colour: ColourMode = .light, typeface: TypefaceMode = .sans) -> some View {
        modifier(TokenThemeModifier(colourMode: colour, typefaceMode: typeface))
    }
}
`;
  },
});

// ─────────────────────────────────────────────────────────────
// MAIN CONFIG
// ─────────────────────────────────────────────────────────────

module.exports = {
  source: ['source-tokens/tokens.json'],

  platforms: {
    css: {
      transforms: [
        'attribute/cti',
        'name/cti/kebab',
        'size/pxToRem',
        'font/familyQuote',
        'color/css',
      ],
      buildPath: 'build-tokens/css/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/standard-modes',
        },
      ],
    },

    tailwind: {
      transforms: ['attribute/cti', 'name/cti/kebab', 'size/pxToRem', 'color/css'],
      buildPath: 'build-tokens/tailwind/',
      files: [
        {
          destination: 'tailwind.config.js',
          format: 'tailwind/standard-modes',
        },
      ],
    },

    flutter: {
      transforms: ['attribute/cti', 'name/cti/camel'],
      buildPath: 'build-tokens/flutter/',
      files: [
        {
          destination: 'app_tokens.dart',
          format: 'flutter/standard-modes',
        },
      ],
    },

    kotlin: {
      transforms: ['attribute/cti', 'name/cti/camel'],
      buildPath: 'build-tokens/android/',
      files: [
        {
          destination: 'Tokens.kt',
          format: 'kotlin/standard-modes',
        },
      ],
    },

    swift: {
      transforms: ['attribute/cti', 'name/cti/camel'],
      buildPath: 'build-tokens/ios/',
      files: [
        {
          destination: 'Tokens.swift',
          format: 'swift/standard-modes',
        },
      ],
    },
  },
};
